In [1]:
import os

In [2]:
# CORPUS_PATH = os.path.join('data', 'austen-brontë-split')
CORPUS_PATH = "/Users/aparajita/Documents/data/austen-brontë-split"

filenames = sorted([os.path.join(CORPUS_PATH, fn) for fn in os.listdir(CORPUS_PATH)])

In [48]:
len(filenames)
type(filenames)

list

In [4]:
filenames[:5]

['/Users/aparajita/Documents/data/austen-bront\xc3\xab-split/Austen_Emma0000.txt',
 '/Users/aparajita/Documents/data/austen-bront\xc3\xab-split/Austen_Emma0001.txt',
 '/Users/aparajita/Documents/data/austen-bront\xc3\xab-split/Austen_Emma0002.txt',
 '/Users/aparajita/Documents/data/austen-bront\xc3\xab-split/Austen_Emma0003.txt',
 '/Users/aparajita/Documents/data/austen-bront\xc3\xab-split/Austen_Emma0004.txt']

In [5]:
import numpy as np  # a conventional alias

import sklearn.feature_extraction.text as text

In [6]:
vectorizer = text.CountVectorizer(input='filename', stop_words='english', min_df=20)

In [14]:
# vectorizer

In [7]:
dtm = vectorizer.fit_transform(filenames).toarray()

In [16]:
print dtm.shape
dtm

(813, 2902)


array([[0, 0, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ..., 
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [8]:
vocab = np.array(vectorizer.get_feature_names())

In [17]:
vocab

array([u'_do_', u'_he_', u'_her_', ..., u'younger', u'youngest', u'youth'], 
      dtype='<U15')

In [18]:
 dtm.shape

(813, 2902)

In [19]:
len(vocab)

2902

In [20]:
from sklearn import decomposition

In [21]:
num_topics = 20

In [22]:
num_top_words = 20

In [23]:
clf = decomposition.NMF(n_components=num_topics, random_state=1)

In [24]:
doctopic = clf.fit_transform(dtm)

In [25]:
topic_words = []
for topic in clf.components_:
    word_idx = np.argsort(topic)[::-1][0:num_top_words]
    topic_words.append([vocab[i] for i in word_idx])

In [27]:
topic_words[0]

[u'know',
 u'think',
 u'like',
 u'man',
 u'good',
 u'say',
 u'does',
 u'said',
 u'oh',
 u'quite',
 u'sure',
 u'yes',
 u'thing',
 u'believe',
 u'way',
 u'love',
 u'young',
 u'people',
 u'better',
 u'thought']

In [28]:
topic_words[1]

[u'mr',
 u'knightley',
 u'rochester',
 u'elton',
 u'man',
 u'did',
 u'think',
 u'evening',
 u'business',
 u'away',
 u'wickham',
 u'gentleman',
 u'time',
 u'dear',
 u'wife',
 u'told',
 u'gentlemen',
 u'brother',
 u'information',
 u'quite']

In [29]:
doctopic = doctopic / np.sum(doctopic, axis=1, keepdims=True)

In [34]:
doctopic

array([[ 0.        ,  0.00506178,  0.00985299, ...,  0.        ,
         0.22786104,  0.        ],
       [ 0.12041777,  0.25543906,  0.        , ...,  0.        ,
         0.23353457,  0.08181409],
       [ 0.12093734,  0.28432916,  0.        , ...,  0.        ,
         0.19369504,  0.0502726 ],
       ..., 
       [ 0.0573295 ,  0.        ,  0.        , ...,  0.08810671,
         0.        ,  0.        ],
       [ 0.064562  ,  0.03481487,  0.        , ...,  0.0627449 ,
         0.        ,  0.06113009],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.12133201]])

In [35]:
novel_names = []

In [36]:
for fn in filenames:
    basename = os.path.basename(fn)
    name, ext = os.path.splitext(basename)
    name = name.rstrip('0123456789')
    novel_names.append(name)

In [37]:
novel_names = np.asarray(novel_names)

In [39]:
# novel_names

In [40]:
doctopic_orig = doctopic.copy()

In [41]:
num_groups = len(set(novel_names))

In [43]:
print set(novel_names)
num_groups

set(['CBronte_Villette', 'Austen_Sense', 'CBronte_Jane', 'Austen_Pride', 'CBronte_Professor', 'Austen_Emma'])


6

In [44]:
doctopic_grouped = np.zeros((num_groups, num_topics))

In [45]:
doctopic_grouped

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [ ]:
for i, name in enumerate(sorted(set(novel_names))):
    doctopic_grouped[i, :] = np.mean(doctopic[novel_names == name, :], axis=0)

In [ ]:
for i, name in enumerate(sorted(set(novel_names))):
    doctopic_grouped[i, :] = np.mean(doctopic[novel_names == name, :], axis=0)

In [ ]:
doctopic = doctopic_grouped

In [ ]:
doctopic

In [ ]:
novels = sorted(set(novel_names))
novels

In [ ]:
print("Top NMF topics in...")
for i in range(len(doctopic)):
    top_topics = np.argsort(doctopic[i,:])[::-1][0:3]
    top_topics_str = ' '.join(str(t) for t in top_topics)
    print("{}: {}".format(novels[i], top_topics_str))

In [ ]:
# show the top 15 words
for t in range(len(topic_words)):
    print("Topic {}: {}".format(t, ' '.join(topic_words[t][:15])))

In [ ]:
austen_indices, cbronte_indices = [], []

for index, fn in enumerate(sorted(set(novel_names))):
    if "Austen" in fn:
        austen_indices.append(index)
    elif "CBronte" in fn:
        cbronte_indices.append(index)

In [ ]:
austen_avg = np.mean(doctopic[austen_indices, :], axis=0)

cbronte_avg = np.mean(doctopic[cbronte_indices, :], axis=0)

keyness = np.abs(austen_avg - cbronte_avg)

In [ ]:
ranking = np.argsort(keyness)[::-1]  # from highest to lowest; [::-1] reverses order in Python sequences

# distinctive topics:
ranking[:10]
